### ISSUE TITLE
RFID Kártya nem érzékel 

### ISSUE THREAD

**Issue by Havasisovago** [Havasisovago/RFID#1]
második nyitásra érzékelő közelébe kerűl a kártya nem fogadja a bejővő jelet és elútasítja a kérést

**Comment by SzenesBence** [comment]
A hiba elhárítva, tökéletesen működik

**Comment by Havasisovago** [comment]
Köszönöm @SzenesBence, #1 megoldva

**Comment by RTamas96** [comment]
Időközönként a kártya olvasó elutasítja a kártyát .Esetleg  tudna @SzenesBence  ehez a hibához megoldást találni ?
